// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Guestbook struct {
	ID      int64
	Message string
}

type PasswordResetToken struct {
	TokenHash string
	UserID    int64
	Expiry    time.Time
}

type Session struct {
	TokenHash string
	UserID    int64
	Expiry    time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
