// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expiry)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	Expiry    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.TokenHash, arg.UserID, arg.Expiry)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, verification_token)
VALUES (?, ?, ?)
RETURNING id, email, password_hash, created_at, verification_token, verified_at
`

type CreateUserParams struct {
	Email             string
	PasswordHash      string
	VerificationToken sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.VerificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT message FROM guestbook WHERE id = 1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getMessage)
	var message string
	err := row.Scan(&message)
	return message, err
}

const getSession = `-- name: GetSession :one
SELECT sessions.token_hash, sessions.user_id, sessions.expiry, users.email FROM sessions
JOIN users ON sessions.user_id = users.id
WHERE token_hash = ? AND expiry > CURRENT_TIMESTAMP LIMIT 1
`

type GetSessionRow struct {
	TokenHash string
	UserID    int64
	Expiry    time.Time
	Email     string
}

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Expiry,
		&i.Email,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, created_at, verification_token, verified_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, verification_token, verified_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO guestbook (id, message) 
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET message = excluded.message
`

func (q *Queries) UpsertMessage(ctx context.Context, message string) error {
	_, err := q.db.ExecContext(ctx, upsertMessage, message)
	return err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users 
SET verified_at = CURRENT_TIMESTAMP, verification_token = NULL
WHERE verification_token = ? AND verified_at IS NULL
RETURNING id
`

func (q *Queries) VerifyUser(ctx context.Context, verificationToken sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, verificationToken)
	var id int64
	err := row.Scan(&id)
	return id, err
}
