// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getMessage = `-- name: GetMessage :one
SELECT message FROM guestbook WHERE id = 1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getMessage)
	var message string
	err := row.Scan(&message)
	return message, err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO guestbook (id, message) 
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET message = excluded.message
`

func (q *Queries) UpsertMessage(ctx context.Context, message string) error {
	_, err := q.db.ExecContext(ctx, upsertMessage, message)
	return err
}
